<x-app-layout>
    @php($party=$customer->party)
    <div class="mx-auto max-w-7xl space-y-6">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Expediente de cliente</p><h1 class="mt-2 text-2xl font-bold text-white">{{ $party->name }}</h1><div class="mt-2 flex flex-wrap gap-2 text-xs"><span class="rounded-full border border-slate-700 px-2.5 py-1 text-slate-300">{{ $party->party_type === 'person' ? 'Persona' : 'Empresa' }}</span><span class="rounded-full border px-2.5 py-1 {{ $customer->active ? 'border-emerald-500/30 text-emerald-200' : 'border-slate-700 text-slate-400' }}">{{ $customer->active ? 'Cliente activo' : 'Cliente inactivo' }}</span>@if($party->supplier)<span class="rounded-full border border-amber-500/30 bg-amber-500/10 px-2.5 py-1 text-amber-200">También proveedor</span>@endif</div></div>@can('manage-customers')<div class="flex gap-2"><a href="{{ route('customers.edit',$customer) }}" class="rounded-xl border border-cyan-400/30 px-4 py-2 text-sm font-semibold text-cyan-200">Editar</a><form method="POST" action="{{ route('customers.toggle-active',$customer) }}">@csrf @method('PATCH')<button class="rounded-xl border border-amber-400/30 px-4 py-2 text-sm font-semibold text-amber-200">{{ $customer->active ? 'Inactivar' : 'Activar' }}</button></form></div>@endcan</div>
        <div class="grid gap-4 md:grid-cols-3"><div class="sulu-card p-5"><p class="text-xs uppercase tracking-wider text-slate-500">Ventas vinculadas</p><p class="mt-2 text-2xl font-bold text-white">{{ $salesCount }}</p></div><div class="sulu-card p-5"><p class="text-xs uppercase tracking-wider text-slate-500">Reparaciones como cliente</p><p class="mt-2 text-2xl font-bold text-white">{{ $serviceCount }}</p></div><div class="sulu-card p-5"><p class="text-xs uppercase tracking-wider text-slate-500">Órdenes como propietario</p><p class="mt-2 text-2xl font-bold text-white">{{ $ownerCount }}</p></div></div>
        <section class="sulu-card p-6"><h2 class="text-lg font-bold text-white">Identidad y contacto</h2><dl class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-xs uppercase text-slate-500">Documento</dt><dd class="mt-1 text-slate-200">{{ $party->tax_id ?: '—' }}</dd></div><div><dt class="text-xs uppercase text-slate-500">Teléfono</dt><dd class="mt-1 text-slate-200">{{ $party->phone ?: '—' }}</dd></div><div><dt class="text-xs uppercase text-slate-500">Correo</dt><dd class="mt-1 text-slate-200">{{ $party->email ?: '—' }}</dd></div><div><dt class="text-xs uppercase text-slate-500">Web</dt><dd class="mt-1 text-slate-200">{{ $party->website ?: '—' }}</dd></div></dl>@if($customer->notes)<div class="mt-5 border-t border-slate-800 pt-4 text-sm text-slate-300">{{ $customer->notes }}</div>@endif</section>
        <section class="sulu-card p-6"><h2 class="text-lg font-bold text-white">Ventas vinculadas</h2><div class="mt-4 space-y-2">@forelse($sales as $sale)<a href="{{ route('commerce-sales.show',$sale) }}" class="flex justify-between rounded-xl border border-slate-800 p-3 text-sm hover:border-cyan-500/30"><span class="text-slate-200">Venta #{{ $sale->sale_number }}</span><span class="font-mono text-slate-400">{{ $sale->currency_code }} {{ number_format($sale->total_minor/100,2,',','.') }}</span></a>@empty<p class="text-sm text-slate-500">Sin ventas vinculadas.</p>@endforelse</div></section>
        <div class="grid gap-6 lg:grid-cols-2"><section class="sulu-card p-6"><h2 class="text-lg font-bold text-white">Reparaciones vinculadas</h2><div class="mt-4 space-y-2">@forelse($serviceOrders as $order)<a href="{{ route('service-orders.show',$order) }}" class="block rounded-xl border border-slate-800 p-3 text-sm hover:border-cyan-500/30"><span class="font-semibold text-slate-200">Orden #{{ $order->order_number }}</span><span class="ml-2 text-slate-500">{{ $order->status->value }}</span></a>@empty<p class="text-sm text-slate-500">Sin reparaciones como cliente.</p>@endforelse</div></section><section class="sulu-card p-6"><h2 class="text-lg font-bold text-white">Equipos / órdenes como propietario</h2><div class="mt-4 space-y-2">@forelse($ownerOrders as $order)<a href="{{ route('service-orders.show',$order) }}" class="block rounded-xl border border-slate-800 p-3 text-sm hover:border-cyan-500/30"><span class="font-semibold text-slate-200">Orden #{{ $order->order_number }}</span><span class="ml-2 text-slate-500">{{ $order->status->value }}</span></a>@empty<p class="text-sm text-slate-500">Sin órdenes como propietario.</p>@endforelse</div></section></div>
    </div>
</x-app-layout>
